// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv9PawjaOb4pOg2dKD7hmCAh4YV46b974',
    appId: '1:766882053270:web:07caec9d51cc4ed61756b7',
    messagingSenderId: '766882053270',
    projectId: 'edspert-advance-learning-adi',
    authDomain: 'edspert-advance-learning-adi.firebaseapp.com',
    storageBucket: 'edspert-advance-learning-adi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmouFJX78j1O_TSs1cmT-qShu_N5KdfO4',
    appId: '1:766882053270:android:5b662f109a8e2d511756b7',
    messagingSenderId: '766882053270',
    projectId: 'edspert-advance-learning-adi',
    storageBucket: 'edspert-advance-learning-adi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwm8l4panMhRdOssCFrExsA51w6ASdCJE',
    appId: '1:766882053270:ios:7c5bfed87fff52131756b7',
    messagingSenderId: '766882053270',
    projectId: 'edspert-advance-learning-adi',
    storageBucket: 'edspert-advance-learning-adi.appspot.com',
    androidClientId: '766882053270-vsmgvkhdaspu55tnlgqga9g7vi88jd0r.apps.googleusercontent.com',
    iosClientId: '766882053270-99v219u7numr6rmjhstj9rrs33br3rer.apps.googleusercontent.com',
    iosBundleId: 'com.example.finproEdspertAdi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwm8l4panMhRdOssCFrExsA51w6ASdCJE',
    appId: '1:766882053270:ios:59f589c9febd740d1756b7',
    messagingSenderId: '766882053270',
    projectId: 'edspert-advance-learning-adi',
    storageBucket: 'edspert-advance-learning-adi.appspot.com',
    androidClientId: '766882053270-vsmgvkhdaspu55tnlgqga9g7vi88jd0r.apps.googleusercontent.com',
    iosClientId: '766882053270-h7fi5gat5d5dvjbsd39boq2r1clr32ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.finproEdspertAdi.RunnerTests',
  );
}
